routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/register', 'Auth\RegisterController@abort')->name('register');
Route::post('/register', 'Auth\RegisterController@abort')->name('register.post');

Route::get('/', 'HomeController@index')->name('home');

Route::get('/plays', 'HomeController@plays')->name('plays');

Route::get('/about', 'HomeController@about')->name('about');

Route::get('/contact', 'HomeController@contact')->name('contact');
Route::post('/contact', 'HomeController@processContact')->name('process.contact');

Route::get('/resources', 'HomeController@resources')->name('resources');

Route::get('/thanks', 'HomeController@thanks')->name('thanks');

Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function() {
	Route::get('/', 'AdminController@dashboard')->name('dashboard');

	Route::resource('users', 'UserController');

	Route::resource('plays', 'PlayController');
});

app/Models/Play.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Play extends Model
{
    //
}

app/Http/Controllers/Admin/PlayController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Play;

class PlayController extends Controller
{
	/**
	 * Show an index of plays.
	 * 
	 * @return \Illuminate\Http\Response
	 */
    public function index()
    {
    	$data['plays'] = Play::orderBy('title')->get();

    	return view('admin.plays.index', $data);
    }

    /**
     * Show the form for creating a new play. 
     * 
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    	return $this->edit(new Play());
    }

    /**
     * Store a newly created play. 
     * 
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    	return $this->update($request, new Play());
    }

    /**
     * Show the form for editing or creating a play.
     * 
     * @param  \App\Models\Play   $play
     * @return \Illuminate\Http\Response
     */
    public function edit(Play $play)
    {
    	$this->authorize('update', $play);

    	$data['play'] = $play;

    	return view('admin.plays.edit', $data);
    }

    /**
     * Update the given play in storage. 
     * 
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Play         $play
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Play $play)
    {
    	$this->authorize('update', $play);

    	$this->validate($request, [
    		'title' => 'required|string|max:255',
    		'text' => 'required|string',
    		'details' => 'required|string|max:255',
            'link' => 'nullable|string|max:255',
    	]);

    	$play->title = $request->input('title');
    	$play->text = $request->input('text');
    	$play->details = $request->input('details');
        $play->link = $request->input('link');

    	$saved = $play->save();

    	if ($saved) {
    		return redirect(route('admin.plays.edit', $play))->with('success', 'Play has been saved.');
    	} else {
    		return redirect(route('admin.plays.edit', $play))->with('danger', 'Something went wrong.');
    	}
    }

    /**
     * Delete a play in storage. 
     * 
     * @param  \App\Models\Play   $play
     * @return \Illuminate\Http\Response
     */
    public function destroy(Play $play)
    {
    	$this->authorize('destroy', $play);

    	$deleted = $play->delete();

    	if ($deleted) {
    		return redirect(route('admin.plays.index'))->with('success', 'Play has been deleted.');
    	} else {
    		return redirect(route('admin.plays.index'))->with('danger', 'Something went wrong.');
    	}
    }
}

resources/views/admin/plays/edit.blade.php
@extends ('layouts.admin')

@section ('content')
<div class="plays-edit-wrapper mb-5">
		@if ($play->id)
			<h1>Edit {{ $play->title }}</h1>
		@else
			<h1>Create New Play</h1>
		@endif

		<form class="basic-form" role="form" action="/admin/plays{{ $play->id ? '/' . $play->id : '' }}" method="POST" autocomplete="force-no">
			@csrf

			@if ($play->id)
				@method('PATCH')
			@endif

			@include ('partials.alerts')

			<div class="form-group">
				<label for="title">Title</label>

				<input id="title" type="text" class="form-control" name="title" value="{{ $play->title ?? old('title') }}">
			</div>

			<div class="form-group">
				<label for="text">Play Text</label>

				<tiny-mce id="text" name="text" value="{{ $play->text ?? old('text') }}"></tiny-mce>
			</div>

			<div class="form-group">
				<label for="details">Details</label>

				<input id="details" type="text" class="form-control" name="details" value="{{ $play->details ?? old('details') }}">
			</div>

			<div class="form-group">
				<label for="link">Link</label>

				<input id="link" type="text" class="form-control" name="link" value="{{ $play->link ?? old('link') }}">
			</div>

            <button class="btn btn-primary" type="submit">Submit/Update Play</button>
		</form>
	</div>
@endsection

resources/views/admin/plays/index.blade.php
@extends ('layouts.admin')

@section ('content')
	<div class="play-index-wrapper">
		<div class="d-flex align-items-center justify-content-between">
			<h1>Plays</h1>

			<a href="{{ route('admin.plays.create') }}">
				<button class="btn btn-primary">
					<i class="fa fa-plus"></i> New Play
				</button>
			</a>
		</div>

		@include ('partials.alerts')

		<table class="table mb-5">
			<thead>
				<th>Title</th>

				<th>Actions</th>

				<th>&nbsp</th>
			</thead>

			<tbody>
				@foreach ($plays as $play)
					<tr>
						<td>
							<a href="{{ route('admin.plays.edit', $play) }}">{{ $play->title }}</a>
						</td>

						<td>
							<a href="{{ route('admin.plays.edit', $play) }}">
								<i title="Edit" class="fa fa-edit"></i>
							</a>
						</td>

						<td>
							<form action="{{ route('admin.plays.destroy', $play) }}" method="POST" onsubmit="if(!confirm('Are you sure? This is permanent.')) return false">
								@csrf @method('DELETE')

								<button type="submit" class="btn btn-danger" style="background-color: white; color: red;">
									<i title="Delete" class="fa fa-trash"></i>
								</button>
							</form>
						</td>
					</tr>
				@endforeach
			</tbody>
		</table>
	</div>
@endsection