routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/register', 'Auth\RegisterController@abort')->name('register');
Route::post('/register', 'Auth\RegisterController@abort')->name('register.post');

Route::get('/', 'HomeController@index')->name('home');

Route::get('/plays', 'HomeController@plays')->name('plays');

Route::get('/about', 'HomeController@about')->name('about');

Route::get('/contact', 'HomeController@contact')->name('contact');
Route::post('/contact', 'HomeController@processContact')->name('process.contact');

Route::get('/resources', 'HomeController@resources')->name('resources');

Route::get('/thanks', 'HomeController@thanks')->name('thanks');

Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function() {
	Route::get('/', 'AdminController@dashboard')->name('dashboard');

	Route::resource('users', 'UserController');

	Route::resource('plays', 'PlayController');
});

resources/views/admin/partials/sidebar.blade.php
<div class="col-sm-3">
	<ul class="admin-nav">
		<li>
			<a href="{{ route('admin.dashboard') }}">Admin Home</a>
		</li>

		<li>
			<a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Log Out</a>

			<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
				@csrf
			</form>
		</li>

		<li>
			<a href="{{ route('admin.plays.index') }}">Plays</a>
		</li>

		<li>
			<a href="{{ route('admin.users.index') }}">Users</a>
		</li>
	</ul>
</div>